#!/bin/bash

architecture=`uname -s`      # computer type e.g. Linux Darwin SunOS

#debug="--extra_debug"
debug=""
CVER=""
LOCATION="-d /opt/esru/esp-r"

if [ "$architecture" == "Darwin" ]; then
#   debug="--extra-debug";
   echo " "
   echo " OS X system, changing install location to /opt/esru/esp-r"
   # Compilers
   CVER="--compiler_version -mp-5"
fi

./Install $1 $LOCATION --xml           --X11 --no_dbs --no_training $debug $CVER --silent
#./Install $1 $LOCATION --xml --SQLite  --X11 --no_dbs --no_training $debug $CVER --silent
#./Install $1 $LOCATION --xml           --X11          --no_training $debug $CVER --silent --force
#./Install $1 $LOCATION --xml           --X11          --no_training $debug $CVER --silent
