#!/bin/bash

architecture=`uname -s`      # computer type e.g. Linux Darwin SunOS

#debug="--extra_debug"
debug=""
CVER=""
LOCATION="-d /opt/esp-r"

if [ "$architecture" == "Darwin" ]; then
#   debug="--extra-debug";
   echo " "
   echo " OS X system, install location /opt/esp-r"
   # Compilers
   CVER="--compiler_version -mp-7"
fi

./Install $1 $LOCATION --xml           --X11 --no_dbs --no_training $debug $CVER --silent --quick_rebuild
#./Install $1 $LOCATION --xml --SQLite  --X11 --no_dbs --no_training $debug $CVER --silent --quick_rebuild
#./Install $1 $LOCATION --xml           --X11          --no_training $debug $CVER --silent --quick_rebuild --force
#./Install $1 $LOCATION --xml           --X11          --no_training $debug $CVER --silent --quick_rebuild
