#!/bin/bash

architecture=`uname -s`      # computer type e.g. Linux Darwin SunOS

debug=""
CVER=""
LOCATION="-d /opt/esru"

if [ "$architecture" == "Darwin" ]; then
#   debug="--extra-debug";
   echo " "
   echo " OS X system, changing install location to /opt/esru"
   # Compilers
   CVER="--compiler_version -mp-4.9"
   LOCATION="-d /opt/esru"
fi

#./Install $1 $LOCATION --xml --X11 --no_dbs --no_training $debug $CVER --silent
./Install $1 $LOCATION --xml --X11          --no_training $debug $CVER --silent
